# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.extension:
        class: AdminBundle\Form\Extension\AppFormTypeExtension
        tags: 
            - { name: form.type_extension, alias: form }

    local_url_exists_validator:
        class: AppBundle\Validator\Constraints\LocalURLExistsValidator
        arguments:
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: local_url_exists_validator }

    app.twig_extension:
        class: AppBundle\Twig\IncludeFileExtention
        public: false
        arguments: [ %web_dir%]
        tags:
            - { name: twig.extension }

    flush.listener:
        class: AdminBundle\Service\onFlushListener
        tags:
            -  {name: doctrine.event_listener, event: onFlush}