<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * Return list aff all article ordered by header
     *
     * @return void
     * @author Michael Strohyi
     **/
    public function findAllByHeader()
    {
        return $this->findBy([], ['header' => 'asc']);
    }

    /**
     * Return article used for homepage
     *
     * @return Article
     * @author Mykola Martynov
     **/
    public function getHomepage()
    {
        return $this->findOneBy(['is_homepage' => true]);
    }

    /**
     * Clear homepage flag for other
     *
     * @param  Article  $article
     * 
     * @return void
     * @author Mykola Martynov
     **/
    public function resetHomepage(Article $article)
    {
        $entity_manager = $this->getEntityManager();

        $query = $entity_manager
            ->createQuery(
                'UPDATE AppBundle:Article a '
                . 'SET a.is_homepage = false '
                . 'WHERE a.is_homepage = true and a.id <> :id'
            )
            ->setParameters([
                    'id' => $article->getId(),
                ]);
        $query->execute();
    }

    /**
     * Get current url for $article from db
     *
     * @param Article $article
     *
     * @return string|null
     * @author Michael Strohyi
     **/
    public function getUrlFromDB($article)
    {
        if (empty($article->getId())) {
            return;
        }
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a.url FROM AppBundle:Article a '
                . 'WHERE a.id = :id'
            )
            ->setParameters([
                'id' => $article->getId(),
            ]);

        return $this->getEntityManager()->getRepository('USPCPageBundle:Page')->getUrlFromRes($query->getOneOrNullResult()['url']);
    }

    /**
     * Return list off all articles with given $type ordered by header
     *
     * @return void
     * @author Michael Strohyi
     **/
    public function findAllByType($type)
    {
        return $this->findBy(['type' => $type], ['header' => 'asc']);
    }

    /**
     * Return list off all articles, which have $subname in header
     *
     * @param string $subname
     * @param int $limit
     * @return array
     * @author Michael Strohyi
     **/
    public function findBySubname($subname, $limit = null)
    {
        if (strlen($subname) < 2) {
            return [];
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Article a '
                . 'WHERE a.header LIKE :subname '
                . 'AND a.type != :type'
            )
            ->setParameters([
                'subname' => '%' . $subname . '%',
                'type' => Article::PAGE_SUBTYPE_INFO,
            ])
            ->setMaxResults($limit);
        return $query->getResult();
    }
}
