<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * Return list aff all article ordered by header
     *
     * @return void
     * @author Michael Strohyi
     **/
    public function findAllByHeader()
    {
        return $this->findBy([], ['header' => 'asc']);
    }
}
