<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Return true if given comment duplicate other comment, which already exists in db for store with given store_id
     *
     * @param Comment $comment
     * @param int $store_id
     *
     * @return boolean
     * @author Michael Strohyi
     **/
    public function commentExists($comment, $store_id)
    {
        return !empty($this->findBy(['label' => $comment->getLabel(), 'author' => $comment->getAuthor(), 'email' => $comment->getEmail(), 'store' => $store_id]));
    }
}
