<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{   
    /**
     * Return true if comment with given label, author, email already exists
     *
     * @param string $label
     * @param string $author
     * @param string $email
     *
     * @return boolean
     * @author Michael Strohyi
     **/
    public function commentExists($label, $author, $email, $store_id)
    {
        return !empty($this->findBy(['label' => $label, 'author' => $author, 'email' => $email, 'store' => $store_id]));
    }
}
