<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends EntityRepository
{
    /**
     * Get link from db for coupon with given $id
     *
     * @param int $id
     *
     * @return string|null
     * @author Michael Strohyi
     **/
    public function findLinkById($id)
    {
        if (empty($id)) {
            return;
        }
        
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c.link FROM AppBundle:Coupon c '
                . 'WHERE c.id = :id'
            )
            ->setParameters([
                'id' => $id,
            ]);

        return $this->getEntityManager()->getRepository('USPCPageBundle:Page')->getUrlFromRes($query->getOneOrNullResult()['link']);
    }

    /**
     * Remove feed coupons from stores, which don't present in given $stores_list
     *
     * @param array $stores_list
     *
     * @return void
     * @author Michael Strohyi
     **/
    public function removeFeedCoupons($stores_list = [])
    {
        $q = 'DELETE FROM AppBundle:StoreCoupon c WHERE c.feedId IS NOT NULL';
        if (!empty($stores_list)) {
            $stores_list = '(' . implode(', ', $stores_list) . ')';
            $q .= ' AND c.store NOT IN ' . $stores_list;
        }

        $query = $this->getEntityManager()->createQuery($q);
        $query->execute();

    }
}
