<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    /**
     * Return list of all menu ordered by name
     *
     * @return Menu[]
     * 
     * @author Mykola Martynov
     **/
    public function findAllByName()
    {
        return $this->findBy([], ['name' => 'ASC']);
    }
}
