<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{

    /**
     * Remove menu items with given $url
     *
     * @param string $url
     *
     * @return void
     * @author Michael Strohyi
     **/
    public function deleteMenuItems($url)
    {
        if (empty($url)) {
            return;
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:MenuItem m '
                . 'WHERE m.url = :url'
            )
            ->setParameters([
                'url' => $url,
            ]);
        $query->execute();
    }
}
