<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorRepository extends EntityRepository
{
    /**
     * Return random operator from db
     *
     * @return Operator|null
     * @author Michael Strohyi
     **/
    public function getRandomName()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('partial o.{id, name}')
           ->from('AppBundle\Entity\Operator', 'o')
           ->orderBy('o.id', 'asc');
        $query = $qb->getQuery();
        $operators = $query->getResult();

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT o.id FROM AppBundle:Operator o ORDER BY o.name ASC'
            );
        $names = $query->getResult();

        return empty($operators) ? null : $operators[rand(0, count($operators) - 1)];
    }
}
