<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorRepository extends EntityRepository
{
    /**
     * Return random operator from db
     *
     * @return Operator|null
     * @author Michael Strohyi
     **/
    public function getRandomOperator()
    {
        $operators = $this->getAllOperators();

        return $this->getRandomItem($operators);
    }

    /**
     * Return all operators from db, except operators with id in exclusions list
     *
     * @return array|null
     * @author Michael Strohyi
     **/
    public function getAllOperators($exclusions = [])
    {
        $q = 'SELECT o FROM AppBundle:Operator o';
        if (!empty($exclusions)) {
            $exclusions = '(' . implode(', ', $exclusions) . ')';
            $q .= ' WHERE o.id NOT IN ' . $exclusions;
        }
        $q .= " ORDER BY o.name ASC";
        $query = $this->getEntityManager()->createQuery($q);

        return $query->getResult();

    }

    /**
     * Return random item from given array
     *
     * @param array $items
     * @return Operator|null
     * @author Michael Strohyi
     **/
    public function getRandomItem($items)
    {
        return empty($items) ? null : $items[rand(0, count($items) - 1)];
    }
}
