<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends EntityRepository
{
    /**
     * Return two lists of urls (first list - real url on server, second list - urls for prod) for all redirects
     *
     * @return array
     * @author Michael Strohyi
     **/
    public function getAllUrls()
    {
        # get all redirects from db
        $redirects = $this->findAll();
        $urls = $prod_urls = [];
        # go through all redirects
        foreach ($redirects as $redirect) {
            # save urls in one list and their prod_urls in other list;
            $urls[] = $redirect->getUrl();
            $prod_urls[] = $redirect->getProdUrl();
        }
        # return lists with results as array
        return [$urls, $prod_urls];
    }
}
