<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends EntityRepository
{
    /**
     * Return two lists of urls (first list - real url on server, second list - urls for prod) for all redirects
     *
     * @return array
     * @author Michael Strohyi
     **/
    public function getAllUrls()
    {
        # get all redirects from db
        $redirects = $this->findAll();
        $urls = $prod_urls = [];
        # go through all redirects
        foreach ($redirects as $redirect) {
            # save urls in one list and their prod_urls in other list;
            $urls[] = $redirect->getUrl();
            $prod_urls[] = $redirect->getProdUrl();
        }
        # return lists with results as array
        return [$urls, $prod_urls];
    }

    /**
     * Return all redirects if their Ids are absent in given exclusions
     *
     * @param array $exclusions
     *
     * @return array
     * @author Michael Strohyi
     **/
    public function getAllRedirects($exclusions = [])
    {
        $q = 'SELECT r FROM AppBundle:Redirect r';
        if (!empty($exclusions)) {
            $exclusions = '(' . implode(', ', $exclusions) . ')';
            $q .= ' WHERE r.id NOT IN ' . $exclusions;
        }

        $query = $this->getEntityManager()->createQuery($q);

        return $query->getResult();
    }
}
